server {
  listen 80;
  root /usr/share/nginx/html;
  index index.html;
  location / { try_files $uri $uri/ /index.html; }
  location /api {
    proxy_pass https://crmtree-backend.salmonsmoke-415d1384.polandcentral.azurecontainerapps.io;
    proxy_set_header Host crmtree-backend.salmonsmoke-415d1384.polandcentral.azurecontainerapps.io;
    proxy_ssl_server_name on;
  }
}